//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class StatusResult {
    
    private string statusField;
    
    private string currentScreenField;
    
    private string responseMessageField;
    
    private string serialNumberField;
    
    private string applicationVersionField;
    
    private string oSVersionField;
    
    private AdditionalParameters additionalParametersField;
    
    private bool removeEMVCardField;
    
    private bool removeEMVCardFieldSpecified;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string CurrentScreen {
        get {
            return this.currentScreenField;
        }
        set {
            this.currentScreenField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
    
    /// <remarks/>
    public string SerialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationVersion {
        get {
            return this.applicationVersionField;
        }
        set {
            this.applicationVersionField = value;
        }
    }
    
    /// <remarks/>
    public string OSVersion {
        get {
            return this.oSVersionField;
        }
        set {
            this.oSVersionField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParameters AdditionalParameters {
        get {
            return this.additionalParametersField;
        }
        set {
            this.additionalParametersField = value;
        }
    }
    
    /// <remarks/>
    public bool RemoveEMVCard {
        get {
            return this.removeEMVCardField;
        }
        set {
            this.removeEMVCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RemoveEMVCardSpecified {
        get {
            return this.removeEMVCardFieldSpecified;
        }
        set {
            this.removeEMVCardFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AdditionalParameters {
    
    private bool paymentDataCapturedField;
    
    private bool paymentDataCapturedFieldSpecified;
    
    private bool removeEMVCardField;
    
    private bool removeEMVCardFieldSpecified;
    
    private string signatureDataField;
    
    private AdditionalParametersAmountDetails amountDetailsField;
    
    private AdditionalParametersEbtDetails ebtDetailsField;
    
    private string trackingIdField;
    
    private AdditionalParametersEMV eMVField;
    
    private AdditionalParametersKeyedDetails keyedDetailsField;
    
    private AdditionalParametersMultiTender multiTenderField;
    
    private AdditionalParametersLoyalty loyaltyField;
    
    /// <remarks/>
    public bool PaymentDataCaptured {
        get {
            return this.paymentDataCapturedField;
        }
        set {
            this.paymentDataCapturedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaymentDataCapturedSpecified {
        get {
            return this.paymentDataCapturedFieldSpecified;
        }
        set {
            this.paymentDataCapturedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool RemoveEMVCard {
        get {
            return this.removeEMVCardField;
        }
        set {
            this.removeEMVCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RemoveEMVCardSpecified {
        get {
            return this.removeEMVCardFieldSpecified;
        }
        set {
            this.removeEMVCardFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string SignatureData {
        get {
            return this.signatureDataField;
        }
        set {
            this.signatureDataField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersAmountDetails AmountDetails {
        get {
            return this.amountDetailsField;
        }
        set {
            this.amountDetailsField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEbtDetails EbtDetails {
        get {
            return this.ebtDetailsField;
        }
        set {
            this.ebtDetailsField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingId {
        get {
            return this.trackingIdField;
        }
        set {
            this.trackingIdField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMV EMV {
        get {
            return this.eMVField;
        }
        set {
            this.eMVField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersKeyedDetails KeyedDetails {
        get {
            return this.keyedDetailsField;
        }
        set {
            this.keyedDetailsField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersMultiTender MultiTender {
        get {
            return this.multiTenderField;
        }
        set {
            this.multiTenderField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersLoyalty Loyalty {
        get {
            return this.loyaltyField;
        }
        set {
            this.loyaltyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersAmountDetails {
    
    private decimal userTipField;
    
    private decimal cashbackField;
    
    private decimal donationField;
    
    private decimal surchargeField;
    
    private string remainingCardBalanceField;
    
    private AdditionalParametersAmountDetailsDiscount[] discountField;
    
    /// <remarks/>
    public decimal UserTip {
        get {
            return this.userTipField;
        }
        set {
            this.userTipField = value;
        }
    }
    
    /// <remarks/>
    public decimal Cashback {
        get {
            return this.cashbackField;
        }
        set {
            this.cashbackField = value;
        }
    }
    
    /// <remarks/>
    public decimal Donation {
        get {
            return this.donationField;
        }
        set {
            this.donationField = value;
        }
    }
    
    /// <remarks/>
    public decimal Surcharge {
        get {
            return this.surchargeField;
        }
        set {
            this.surchargeField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingCardBalance {
        get {
            return this.remainingCardBalanceField;
        }
        set {
            this.remainingCardBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Discount")]
    public AdditionalParametersAmountDetailsDiscount[] Discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersAmountDetailsDiscount {
    
    private decimal totalField;
    
    /// <remarks/>
    public decimal Total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEbtDetails {
    
    private string ebtTypeField;
    
    private AdditionalParametersEbtDetailsBalances balancesField;
    
    /// <remarks/>
    public string EbtType {
        get {
            return this.ebtTypeField;
        }
        set {
            this.ebtTypeField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEbtDetailsBalances Balances {
        get {
            return this.balancesField;
        }
        set {
            this.balancesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEbtDetailsBalances {
    
    private decimal cashAvailableBalanceField;
    
    private decimal snapAvailableBalanceField;
    
    /// <remarks/>
    public decimal CashAvailableBalance {
        get {
            return this.cashAvailableBalanceField;
        }
        set {
            this.cashAvailableBalanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal SnapAvailableBalance {
        get {
            return this.snapAvailableBalanceField;
        }
        set {
            this.snapAvailableBalanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMV {
    
    private AdditionalParametersEMVApplicationInformation applicationInformationField;
    
    private AdditionalParametersEMVCardInformation cardInformationField;
    
    private AdditionalParametersEMVApplicationCryptogram applicationCryptogramField;
    
    private string cvmResultsField;
    
    private string issuerApplicationDataField;
    
    private string terminalVerificationResultsField;
    
    private string unpredictableNumberField;
    
    private AdditionalParametersEMVAmount amountField;
    
    private string posEntryModeField;
    
    private AdditionalParametersEMVTerminalInformation terminalInformationField;
    
    private AdditionalParametersEMVTransactionInformation transactionInformationField;
    
    private string cryptogramInformationDataField;
    
    private string pINStatementField;
    
    private string cvmMethodField;
    
    private string issuerActionCodeDefaultField;
    
    private string issuerActionCodeDenialField;
    
    private string issuerActionCodeOnlineField;
    
    private string authorizationResponseCodeField;
    
    /// <remarks/>
    public AdditionalParametersEMVApplicationInformation ApplicationInformation {
        get {
            return this.applicationInformationField;
        }
        set {
            this.applicationInformationField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMVCardInformation CardInformation {
        get {
            return this.cardInformationField;
        }
        set {
            this.cardInformationField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMVApplicationCryptogram ApplicationCryptogram {
        get {
            return this.applicationCryptogramField;
        }
        set {
            this.applicationCryptogramField = value;
        }
    }
    
    /// <remarks/>
    public string CvmResults {
        get {
            return this.cvmResultsField;
        }
        set {
            this.cvmResultsField = value;
        }
    }
    
    /// <remarks/>
    public string IssuerApplicationData {
        get {
            return this.issuerApplicationDataField;
        }
        set {
            this.issuerApplicationDataField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalVerificationResults {
        get {
            return this.terminalVerificationResultsField;
        }
        set {
            this.terminalVerificationResultsField = value;
        }
    }
    
    /// <remarks/>
    public string UnpredictableNumber {
        get {
            return this.unpredictableNumberField;
        }
        set {
            this.unpredictableNumberField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMVAmount Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string PosEntryMode {
        get {
            return this.posEntryModeField;
        }
        set {
            this.posEntryModeField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMVTerminalInformation TerminalInformation {
        get {
            return this.terminalInformationField;
        }
        set {
            this.terminalInformationField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersEMVTransactionInformation TransactionInformation {
        get {
            return this.transactionInformationField;
        }
        set {
            this.transactionInformationField = value;
        }
    }
    
    /// <remarks/>
    public string CryptogramInformationData {
        get {
            return this.cryptogramInformationDataField;
        }
        set {
            this.cryptogramInformationDataField = value;
        }
    }
    
    /// <remarks/>
    public string PINStatement {
        get {
            return this.pINStatementField;
        }
        set {
            this.pINStatementField = value;
        }
    }
    
    /// <remarks/>
    public string CvmMethod {
        get {
            return this.cvmMethodField;
        }
        set {
            this.cvmMethodField = value;
        }
    }
    
    /// <remarks/>
    public string IssuerActionCodeDefault {
        get {
            return this.issuerActionCodeDefaultField;
        }
        set {
            this.issuerActionCodeDefaultField = value;
        }
    }
    
    /// <remarks/>
    public string IssuerActionCodeDenial {
        get {
            return this.issuerActionCodeDenialField;
        }
        set {
            this.issuerActionCodeDenialField = value;
        }
    }
    
    /// <remarks/>
    public string IssuerActionCodeOnline {
        get {
            return this.issuerActionCodeOnlineField;
        }
        set {
            this.issuerActionCodeOnlineField = value;
        }
    }
    
    /// <remarks/>
    public string AuthorizationResponseCode {
        get {
            return this.authorizationResponseCodeField;
        }
        set {
            this.authorizationResponseCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVApplicationInformation {
    
    private string aidField;
    
    private string applicationLabelField;
    
    private string applicationExpiryDateField;
    
    private string applicationEffectiveDateField;
    
    private string applicationInterchangeProfileField;
    
    private string applicationVersionNumberField;
    
    private string applicationTransactionCounterField;
    
    private string applicationUsageControlField;
    
    private string applicationPreferredNameField;
    
    private string applicationDisplayNameField;
    
    /// <remarks/>
    public string Aid {
        get {
            return this.aidField;
        }
        set {
            this.aidField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationLabel {
        get {
            return this.applicationLabelField;
        }
        set {
            this.applicationLabelField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationExpiryDate {
        get {
            return this.applicationExpiryDateField;
        }
        set {
            this.applicationExpiryDateField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationEffectiveDate {
        get {
            return this.applicationEffectiveDateField;
        }
        set {
            this.applicationEffectiveDateField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationInterchangeProfile {
        get {
            return this.applicationInterchangeProfileField;
        }
        set {
            this.applicationInterchangeProfileField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationVersionNumber {
        get {
            return this.applicationVersionNumberField;
        }
        set {
            this.applicationVersionNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationTransactionCounter {
        get {
            return this.applicationTransactionCounterField;
        }
        set {
            this.applicationTransactionCounterField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationUsageControl {
        get {
            return this.applicationUsageControlField;
        }
        set {
            this.applicationUsageControlField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationPreferredName {
        get {
            return this.applicationPreferredNameField;
        }
        set {
            this.applicationPreferredNameField = value;
        }
    }
    
    /// <remarks/>
    public string ApplicationDisplayName {
        get {
            return this.applicationDisplayNameField;
        }
        set {
            this.applicationDisplayNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVCardInformation {
    
    private string maskedPanField;
    
    private string panSequenceNumberField;
    
    private string cardExpiryDateField;
    
    /// <remarks/>
    public string MaskedPan {
        get {
            return this.maskedPanField;
        }
        set {
            this.maskedPanField = value;
        }
    }
    
    /// <remarks/>
    public string PanSequenceNumber {
        get {
            return this.panSequenceNumberField;
        }
        set {
            this.panSequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string CardExpiryDate {
        get {
            return this.cardExpiryDateField;
        }
        set {
            this.cardExpiryDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVApplicationCryptogram {
    
    private string cryptogramTypeField;
    
    private string cryptogramField;
    
    /// <remarks/>
    public string CryptogramType {
        get {
            return this.cryptogramTypeField;
        }
        set {
            this.cryptogramTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Cryptogram {
        get {
            return this.cryptogramField;
        }
        set {
            this.cryptogramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVAmount {
    
    private decimal amountAuthorizedField;
    
    private decimal amountOtherField;
    
    /// <remarks/>
    public decimal AmountAuthorized {
        get {
            return this.amountAuthorizedField;
        }
        set {
            this.amountAuthorizedField = value;
        }
    }
    
    /// <remarks/>
    public decimal AmountOther {
        get {
            return this.amountOtherField;
        }
        set {
            this.amountOtherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVTerminalInformation {
    
    private string terminalTypeField;
    
    private string ifdSerialNumberField;
    
    private string terminalCountryCodeField;
    
    private string terminalIDField;
    
    private string terminalActionCodeDefaultField;
    
    private string terminalActionCodeDenialField;
    
    private string terminalActionCodeOnlineField;
    
    /// <remarks/>
    public string TerminalType {
        get {
            return this.terminalTypeField;
        }
        set {
            this.terminalTypeField = value;
        }
    }
    
    /// <remarks/>
    public string IfdSerialNumber {
        get {
            return this.ifdSerialNumberField;
        }
        set {
            this.ifdSerialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalCountryCode {
        get {
            return this.terminalCountryCodeField;
        }
        set {
            this.terminalCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalID {
        get {
            return this.terminalIDField;
        }
        set {
            this.terminalIDField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalActionCodeDefault {
        get {
            return this.terminalActionCodeDefaultField;
        }
        set {
            this.terminalActionCodeDefaultField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalActionCodeDenial {
        get {
            return this.terminalActionCodeDenialField;
        }
        set {
            this.terminalActionCodeDenialField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalActionCodeOnline {
        get {
            return this.terminalActionCodeOnlineField;
        }
        set {
            this.terminalActionCodeOnlineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersEMVTransactionInformation {
    
    private string transactionTypeField;
    
    private string transactionCurrencyCodeField;
    
    private string transactionStatusInformationField;
    
    /// <remarks/>
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionCurrencyCode {
        get {
            return this.transactionCurrencyCodeField;
        }
        set {
            this.transactionCurrencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionStatusInformation {
        get {
            return this.transactionStatusInformationField;
        }
        set {
            this.transactionStatusInformationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersKeyedDetails {
    
    private string expirationDateField;
    
    private string avsStreetZipCodeField;
    
    private string avsResponseField;
    
    private string cvResponseField;
    
    /// <remarks/>
    public string ExpirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }
    
    /// <remarks/>
    public string AvsStreetZipCode {
        get {
            return this.avsStreetZipCodeField;
        }
        set {
            this.avsStreetZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string AvsResponse {
        get {
            return this.avsResponseField;
        }
        set {
            this.avsResponseField = value;
        }
    }
    
    /// <remarks/>
    public string CvResponse {
        get {
            return this.cvResponseField;
        }
        set {
            this.cvResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersMultiTender {
    
    private AdditionalParametersMultiTenderTransaction[] transactionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Transaction", IsNullable=false)]
    public AdditionalParametersMultiTenderTransaction[] Transactions {
        get {
            return this.transactionsField;
        }
        set {
            this.transactionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersMultiTenderTransaction {
    
    private string statusField;
    
    private string errorMessageField;
    
    private decimal amountRequestedField;
    
    private decimal amountApprovedField;
    
    private string accountNumberField;
    
    private string tokenField;
    
    private string transactionTypeField;
    
    private string paymentTypeField;
    
    private AdditionalParametersMultiTenderTransactionReward rewardField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public decimal AmountRequested {
        get {
            return this.amountRequestedField;
        }
        set {
            this.amountRequestedField = value;
        }
    }
    
    /// <remarks/>
    public decimal AmountApproved {
        get {
            return this.amountApprovedField;
        }
        set {
            this.amountApprovedField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentType {
        get {
            return this.paymentTypeField;
        }
        set {
            this.paymentTypeField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersMultiTenderTransactionReward Reward {
        get {
            return this.rewardField;
        }
        set {
            this.rewardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersMultiTenderTransactionReward {
    
    private string errorMessageField;
    
    private string accountNumberField;
    
    private string typeField;
    
    private string quantityField;
    
    private string tokenField;
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersLoyalty {
    
    private string accountNumberField;
    
    private AdditionalParametersLoyaltyBalances balancesField;
    
    private string pointsEarnedField;
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParametersLoyaltyBalances Balances {
        get {
            return this.balancesField;
        }
        set {
            this.balancesField = value;
        }
    }
    
    /// <remarks/>
    public string PointsEarned {
        get {
            return this.pointsEarnedField;
        }
        set {
            this.pointsEarnedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AdditionalParametersLoyaltyBalances {
    
    private string pointsBalanceField;
    
    private string amountBalanceField;
    
    /// <remarks/>
    public string PointsBalance {
        get {
            return this.pointsBalanceField;
        }
        set {
            this.pointsBalanceField = value;
        }
    }
    
    /// <remarks/>
    public string AmountBalance {
        get {
            return this.amountBalanceField;
        }
        set {
            this.amountBalanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CancelResult {
    
    private string statusField;
    
    private string responseMessageField;
    
    private string additionalParametersField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
    
    /// <remarks/>
    public string AdditionalParameters {
        get {
            return this.additionalParametersField;
        }
        set {
            this.additionalParametersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OrderResult {
    
    private string statusField;
    
    private string responseMessageField;
    
    private decimal itemsField;
    
    private bool itemsFieldSpecified;
    
    private decimal discountsField;
    
    private bool discountsFieldSpecified;
    
    private decimal totalAmountField;
    
    private bool totalAmountFieldSpecified;
    
    private string customSubTotalField;
    
    private decimal taxAmountField;
    
    private bool taxAmountFieldSpecified;
    
    private string itemIDField;
    
    private AdditionalParameters additionalParametersField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
    
    /// <remarks/>
    public decimal Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemsSpecified {
        get {
            return this.itemsFieldSpecified;
        }
        set {
            this.itemsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Discounts {
        get {
            return this.discountsField;
        }
        set {
            this.discountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DiscountsSpecified {
        get {
            return this.discountsFieldSpecified;
        }
        set {
            this.discountsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalAmount {
        get {
            return this.totalAmountField;
        }
        set {
            this.totalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalAmountSpecified {
        get {
            return this.totalAmountFieldSpecified;
        }
        set {
            this.totalAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CustomSubTotal {
        get {
            return this.customSubTotalField;
        }
        set {
            this.customSubTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal TaxAmount {
        get {
            return this.taxAmountField;
        }
        set {
            this.taxAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TaxAmountSpecified {
        get {
            return this.taxAmountFieldSpecified;
        }
        set {
            this.taxAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ItemID {
        get {
            return this.itemIDField;
        }
        set {
            this.itemIDField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParameters AdditionalParameters {
        get {
            return this.additionalParametersField;
        }
        set {
            this.additionalParametersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OrderSnapshot {
    
    private string statusField;
    
    private string responseMessageField;
    
    private string orderNumberField;
    
    private string numberOfItemsField;
    
    private decimal orderTaxField;
    
    private bool orderTaxFieldSpecified;
    
    private decimal orderTotalField;
    
    private bool orderTotalFieldSpecified;
    
    private OrderSnapshotItem[] itemsField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
    
    /// <remarks/>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public string NumberOfItems {
        get {
            return this.numberOfItemsField;
        }
        set {
            this.numberOfItemsField = value;
        }
    }
    
    /// <remarks/>
    public decimal OrderTax {
        get {
            return this.orderTaxField;
        }
        set {
            this.orderTaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderTaxSpecified {
        get {
            return this.orderTaxFieldSpecified;
        }
        set {
            this.orderTaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal OrderTotal {
        get {
            return this.orderTotalField;
        }
        set {
            this.orderTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrderTotalSpecified {
        get {
            return this.orderTotalFieldSpecified;
        }
        set {
            this.orderTotalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public OrderSnapshotItem[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class OrderSnapshotItem {
    
    private string itemRequestTypeField;
    
    private string itemIDField;
    
    private string itemQuantityField;
    
    private decimal itemAmountField;
    
    private decimal itemTotalAmountField;
    
    private decimal itemTaxAmountField;
    
    private decimal itemTaxTotalField;
    
    private string itemTypeField;
    
    private string itemTypeValueField;
    
    private string itemUPCField;
    
    private string itemDescriptionField;
    
    private string itemCategoryField;
    
    /// <remarks/>
    public string ItemRequestType {
        get {
            return this.itemRequestTypeField;
        }
        set {
            this.itemRequestTypeField = value;
        }
    }
    
    /// <remarks/>
    public string itemID {
        get {
            return this.itemIDField;
        }
        set {
            this.itemIDField = value;
        }
    }
    
    /// <remarks/>
    public string itemQuantity {
        get {
            return this.itemQuantityField;
        }
        set {
            this.itemQuantityField = value;
        }
    }
    
    /// <remarks/>
    public decimal itemAmount {
        get {
            return this.itemAmountField;
        }
        set {
            this.itemAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal itemTotalAmount {
        get {
            return this.itemTotalAmountField;
        }
        set {
            this.itemTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal itemTaxAmount {
        get {
            return this.itemTaxAmountField;
        }
        set {
            this.itemTaxAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal itemTaxTotal {
        get {
            return this.itemTaxTotalField;
        }
        set {
            this.itemTaxTotalField = value;
        }
    }
    
    /// <remarks/>
    public string itemType {
        get {
            return this.itemTypeField;
        }
        set {
            this.itemTypeField = value;
        }
    }
    
    /// <remarks/>
    public string itemTypeValue {
        get {
            return this.itemTypeValueField;
        }
        set {
            this.itemTypeValueField = value;
        }
    }
    
    /// <remarks/>
    public string itemUPC {
        get {
            return this.itemUPCField;
        }
        set {
            this.itemUPCField = value;
        }
    }
    
    /// <remarks/>
    public string itemDescription {
        get {
            return this.itemDescriptionField;
        }
        set {
            this.itemDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string itemCategory {
        get {
            return this.itemCategoryField;
        }
        set {
            this.itemCategoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InitiateKeyedEntryResult {
    
    private string statusField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class TransactionResult {
    
    private string statusField;
    
    private decimal amountApprovedField;
    
    private string authorizationCodeField;
    
    private string cardHolderField;
    
    private string cardholderField;
    
    private string accountNumberField;
    
    private string paymentTypeField;
    
    private string entryModeField;
    
    private string errorMessageField;
    
    private string tokenField;
    
    private string transactionDateField;
    
    private string transactionTypeField;
    
    private string responseTypeField;
    
    private string validationKeyField;
    
    private AdditionalParameters additionalParametersField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public decimal AmountApproved {
        get {
            return this.amountApprovedField;
        }
        set {
            this.amountApprovedField = value;
        }
    }
    
    /// <remarks/>
    public string AuthorizationCode {
        get {
            return this.authorizationCodeField;
        }
        set {
            this.authorizationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CardHolder {
        get {
            return this.cardHolderField;
        }
        set {
            this.cardHolderField = value;
        }
    }
    
    /// <remarks/>
    public string Cardholder {
        get {
            return this.cardholderField;
        }
        set {
            this.cardholderField = value;
        }
    }
    
    /// <remarks/>
    public string AccountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public string PaymentType {
        get {
            return this.paymentTypeField;
        }
        set {
            this.paymentTypeField = value;
        }
    }
    
    /// <remarks/>
    public string EntryMode {
        get {
            return this.entryModeField;
        }
        set {
            this.entryModeField = value;
        }
    }
    
    /// <remarks/>
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public string Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionDate {
        get {
            return this.transactionDateField;
        }
        set {
            this.transactionDateField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionType {
        get {
            return this.transactionTypeField;
        }
        set {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseType {
        get {
            return this.responseTypeField;
        }
        set {
            this.responseTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ValidationKey {
        get {
            return this.validationKeyField;
        }
        set {
            this.validationKeyField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalParameters AdditionalParameters {
        get {
            return this.additionalParametersField;
        }
        set {
            this.additionalParametersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AgreementTextResponse {
    
    private string requestIDField;
    
    private string statusField;
    
    /// <remarks/>
    public string RequestID {
        get {
            return this.requestIDField;
        }
        set {
            this.requestIDField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GetSignatureResult {
    
    private string statusField;
    
    private string signatureDataField;
    
    private string requestIDField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string SignatureData {
        get {
            return this.signatureDataField;
        }
        set {
            this.signatureDataField = value;
        }
    }
    
    /// <remarks/>
    public string RequestID {
        get {
            return this.requestIDField;
        }
        set {
            this.requestIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class GetCustomerInputResponse {
    
    private string statusField;
    
    private string requestIDField;
    
    private GetCustomerInputResponseValue[] valuesField;
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string RequestID {
        get {
            return this.requestIDField;
        }
        set {
            this.requestIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable=false)]
    public GetCustomerInputResponseValue[] Values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class GetCustomerInputResponseValue {
    
    private string inputTypeField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string inputType {
        get {
            return this.inputTypeField;
        }
        set {
            this.inputTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
