//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayanCheckoutSample.MerchantWARE45 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/", ConfigurationName="MerchantWARE45.CreditSoap")]
    public interface CreditSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/AdjustTip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 AdjustTip(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.TipRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/AdjustTip", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> AdjustTipAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.TipRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/AttachSignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.SignatureResponse45 AttachSignature(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.SignatureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/AttachSignature", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.SignatureResponse45> AttachSignatureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.SignatureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Authorize(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.AuthorizationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> AuthorizeAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.AuthorizationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/BoardCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 BoardCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.BoardingRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/BoardCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> BoardCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.BoardingRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/UpdateBoardedCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 UpdateBoardedCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.UpdateBoardedCardRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/UpdateBoardedCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> UpdateBoardedCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.UpdateBoardedCardRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Capture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Capture(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.CaptureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Capture", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> CaptureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.CaptureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/FindBoardedCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.VaultTokenResponse45 FindBoardedCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/FindBoardedCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultTokenResponse45> FindBoardedCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/ForceCapture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 ForceCapture(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.ForceCaptureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/ForceCapture", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> ForceCaptureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.ForceCaptureRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Refund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Refund(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.RefundRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Refund", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> RefundAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.RefundRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Sale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Sale(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.SaleRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Sale", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> SaleAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.SaleRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/SettleBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.BatchResponse45 SettleBatch(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/SettleBatch", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.BatchResponse45> SettleBatchAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/UnboardCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 UnboardCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/UnboardCard", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> UnboardCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Void", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Void(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VoidRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.merchantwarehouse.com/merchantware/v45/Void", ReplyAction="*")]
        System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> VoidAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VoidRequest Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class MerchantCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantNameField;
        
        private string merchantSiteIdField;
        
        private string merchantKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantName {
            get {
                return this.merchantNameField;
            }
            set {
                this.merchantNameField = value;
                this.RaisePropertyChanged("MerchantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MerchantSiteId {
            get {
                return this.merchantSiteIdField;
            }
            set {
                this.merchantSiteIdField = value;
                this.RaisePropertyChanged("MerchantSiteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MerchantKey {
            get {
                return this.merchantKeyField;
            }
            set {
                this.merchantKeyField = value;
                this.RaisePropertyChanged("MerchantKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class VoidRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class BatchResponse45 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchStatusField;
        
        private string authorizationCodeField;
        
        private string batchAmountField;
        
        private int transactionCountField;
        
        private string transactionDateField;
        
        private string errorMessageField;
        
        private string extraDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BatchStatus {
            get {
                return this.batchStatusField;
            }
            set {
                this.batchStatusField = value;
                this.RaisePropertyChanged("BatchStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("AuthorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BatchAmount {
            get {
                return this.batchAmountField;
            }
            set {
                this.batchAmountField = value;
                this.RaisePropertyChanged("BatchAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TransactionCount {
            get {
                return this.transactionCountField;
            }
            set {
                this.transactionCountField = value;
                this.RaisePropertyChanged("TransactionCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ExtraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
                this.RaisePropertyChanged("ExtraData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class HealthCareAmountDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string copayAmountField;
        
        private string clinicalAmountField;
        
        private string dentalAmountField;
        
        private string healthCareTotalAmountField;
        
        private string prescriptionAmountField;
        
        private string visionAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CopayAmount {
            get {
                return this.copayAmountField;
            }
            set {
                this.copayAmountField = value;
                this.RaisePropertyChanged("CopayAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ClinicalAmount {
            get {
                return this.clinicalAmountField;
            }
            set {
                this.clinicalAmountField = value;
                this.RaisePropertyChanged("ClinicalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DentalAmount {
            get {
                return this.dentalAmountField;
            }
            set {
                this.dentalAmountField = value;
                this.RaisePropertyChanged("DentalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string HealthCareTotalAmount {
            get {
                return this.healthCareTotalAmountField;
            }
            set {
                this.healthCareTotalAmountField = value;
                this.RaisePropertyChanged("HealthCareTotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PrescriptionAmount {
            get {
                return this.prescriptionAmountField;
            }
            set {
                this.prescriptionAmountField = value;
                this.RaisePropertyChanged("PrescriptionAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VisionAmount {
            get {
                return this.visionAmountField;
            }
            set {
                this.visionAmountField = value;
                this.RaisePropertyChanged("VisionAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class SaleRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string cashbackAmountField;
        
        private string surchargeAmountField;
        
        private string taxAmountField;
        
        private HealthCareAmountDetails healthCareAmountDetailsField;
        
        private string invoiceNumberField;
        
        private string purchaseOrderNumberField;
        
        private string customerCodeField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        private string enablePartialAuthorizationField;
        
        private string forceDuplicateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CashbackAmount {
            get {
                return this.cashbackAmountField;
            }
            set {
                this.cashbackAmountField = value;
                this.RaisePropertyChanged("CashbackAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SurchargeAmount {
            get {
                return this.surchargeAmountField;
            }
            set {
                this.surchargeAmountField = value;
                this.RaisePropertyChanged("SurchargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public HealthCareAmountDetails HealthCareAmountDetails {
            get {
                return this.healthCareAmountDetailsField;
            }
            set {
                this.healthCareAmountDetailsField = value;
                this.RaisePropertyChanged("HealthCareAmountDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PurchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("PurchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("CustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EnablePartialAuthorization {
            get {
                return this.enablePartialAuthorizationField;
            }
            set {
                this.enablePartialAuthorizationField = value;
                this.RaisePropertyChanged("EnablePartialAuthorization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ForceDuplicate {
            get {
                return this.forceDuplicateField;
            }
            set {
                this.forceDuplicateField = value;
                this.RaisePropertyChanged("ForceDuplicate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class RefundRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string invoiceNumberField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class ForceCaptureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string authorizationCodeField;
        
        private string invoiceNumberField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("AuthorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class VaultTokenResponse45 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cardNumberField;
        
        private string expirationDateField;
        
        private string cardholderField;
        
        private string cardTypeField;
        
        private string avsStreetAddressField;
        
        private string avsZipCodeField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cardholder {
            get {
                return this.cardholderField;
            }
            set {
                this.cardholderField = value;
                this.RaisePropertyChanged("Cardholder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AvsStreetAddress {
            get {
                return this.avsStreetAddressField;
            }
            set {
                this.avsStreetAddressField = value;
                this.RaisePropertyChanged("AvsStreetAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AvsZipCode {
            get {
                return this.avsZipCodeField;
            }
            set {
                this.avsZipCodeField = value;
                this.RaisePropertyChanged("AvsZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class VaultTokenRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vaultTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VaultToken {
            get {
                return this.vaultTokenField;
            }
            set {
                this.vaultTokenField = value;
                this.RaisePropertyChanged("VaultToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class CaptureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string amountField;
        
        private string invoiceNumberField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class UpdateBoardedCardRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vaultTokenField;
        
        private string expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VaultToken {
            get {
                return this.vaultTokenField;
            }
            set {
                this.vaultTokenField = value;
                this.RaisePropertyChanged("VaultToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class VaultBoardingResponse45 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vaultTokenField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VaultToken {
            get {
                return this.vaultTokenField;
            }
            set {
                this.vaultTokenField = value;
                this.RaisePropertyChanged("VaultToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class BoardingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantDefinedTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantDefinedToken {
            get {
                return this.merchantDefinedTokenField;
            }
            set {
                this.merchantDefinedTokenField = value;
                this.RaisePropertyChanged("MerchantDefinedToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class AuthorizationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string invoiceNumberField;
        
        private string registerNumberField;
        
        private string merchantTransactionIdField;
        
        private string cardAcceptorTerminalIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MerchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
                this.RaisePropertyChanged("MerchantTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CardAcceptorTerminalId {
            get {
                return this.cardAcceptorTerminalIdField;
            }
            set {
                this.cardAcceptorTerminalIdField = value;
                this.RaisePropertyChanged("CardAcceptorTerminalId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class PaymentData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceField;
        
        private string trackDataField;
        
        private string pinBlockField;
        
        private string pinKsnField;
        
        private string readerEntryModeField;
        
        private string cardNumberField;
        
        private string expirationDateField;
        
        private string cardHolderField;
        
        private string avsStreetAddressField;
        
        private string avsZipCodeField;
        
        private string cardVerificationValueField;
        
        private string tokenField;
        
        private string vaultTokenField;
        
        private string customerEmailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrackData {
            get {
                return this.trackDataField;
            }
            set {
                this.trackDataField = value;
                this.RaisePropertyChanged("TrackData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PinBlock {
            get {
                return this.pinBlockField;
            }
            set {
                this.pinBlockField = value;
                this.RaisePropertyChanged("PinBlock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PinKsn {
            get {
                return this.pinKsnField;
            }
            set {
                this.pinKsnField = value;
                this.RaisePropertyChanged("PinKsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReaderEntryMode {
            get {
                return this.readerEntryModeField;
            }
            set {
                this.readerEntryModeField = value;
                this.RaisePropertyChanged("ReaderEntryMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CardHolder {
            get {
                return this.cardHolderField;
            }
            set {
                this.cardHolderField = value;
                this.RaisePropertyChanged("CardHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AvsStreetAddress {
            get {
                return this.avsStreetAddressField;
            }
            set {
                this.avsStreetAddressField = value;
                this.RaisePropertyChanged("AvsStreetAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AvsZipCode {
            get {
                return this.avsZipCodeField;
            }
            set {
                this.avsZipCodeField = value;
                this.RaisePropertyChanged("AvsZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CardVerificationValue {
            get {
                return this.cardVerificationValueField;
            }
            set {
                this.cardVerificationValueField = value;
                this.RaisePropertyChanged("CardVerificationValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string VaultToken {
            get {
                return this.vaultTokenField;
            }
            set {
                this.vaultTokenField = value;
                this.RaisePropertyChanged("VaultToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomerEmailAddress {
            get {
                return this.customerEmailAddressField;
            }
            set {
                this.customerEmailAddressField = value;
                this.RaisePropertyChanged("CustomerEmailAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class SignatureResponse45 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uploadStatusField;
        
        private string tokenField;
        
        private string transactionDateField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UploadStatus {
            get {
                return this.uploadStatusField;
            }
            set {
                this.uploadStatusField = value;
                this.RaisePropertyChanged("UploadStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class SignatureRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string vectorImageDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VectorImageData {
            get {
                return this.vectorImageDataField;
            }
            set {
                this.vectorImageDataField = value;
                this.RaisePropertyChanged("VectorImageData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class FraudScoring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string externalReferenceField;
        
        private string recommendationField;
        
        private string scoreField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
                this.RaisePropertyChanged("ExternalReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Recommendation {
            get {
                return this.recommendationField;
            }
            set {
                this.recommendationField = value;
                this.RaisePropertyChanged("Recommendation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("Score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class TransactionResponse45 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string approvalStatusField;
        
        private string tokenField;
        
        private string authorizationCodeField;
        
        private string transactionDateField;
        
        private string amountField;
        
        private string remainingCardBalanceField;
        
        private string cardNumberField;
        
        private string cardholderField;
        
        private string cardTypeField;
        
        private string fsaCardField;
        
        private string readerEntryModeField;
        
        private string avsResponseField;
        
        private string cvResponseField;
        
        private string errorMessageField;
        
        private string extraDataField;
        
        private FraudScoring fraudScoringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApprovalStatus {
            get {
                return this.approvalStatusField;
            }
            set {
                this.approvalStatusField = value;
                this.RaisePropertyChanged("ApprovalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
                this.RaisePropertyChanged("AuthorizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RemainingCardBalance {
            get {
                return this.remainingCardBalanceField;
            }
            set {
                this.remainingCardBalanceField = value;
                this.RaisePropertyChanged("RemainingCardBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Cardholder {
            get {
                return this.cardholderField;
            }
            set {
                this.cardholderField = value;
                this.RaisePropertyChanged("Cardholder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FsaCard {
            get {
                return this.fsaCardField;
            }
            set {
                this.fsaCardField = value;
                this.RaisePropertyChanged("FsaCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ReaderEntryMode {
            get {
                return this.readerEntryModeField;
            }
            set {
                this.readerEntryModeField = value;
                this.RaisePropertyChanged("ReaderEntryMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AvsResponse {
            get {
                return this.avsResponseField;
            }
            set {
                this.avsResponseField = value;
                this.RaisePropertyChanged("AvsResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CvResponse {
            get {
                return this.cvResponseField;
            }
            set {
                this.cvResponseField = value;
                this.RaisePropertyChanged("CvResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ExtraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
                this.RaisePropertyChanged("ExtraData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public FraudScoring FraudScoring {
            get {
                return this.fraudScoringField;
            }
            set {
                this.fraudScoringField = value;
                this.RaisePropertyChanged("FraudScoring");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36373")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.merchantwarehouse.com/merchantware/v45/")]
    public partial class TipRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditSoapChannel : CayanCheckoutSample.MerchantWARE45.CreditSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditSoapClient : System.ServiceModel.ClientBase<CayanCheckoutSample.MerchantWARE45.CreditSoap>, CayanCheckoutSample.MerchantWARE45.CreditSoap {
        
        public CreditSoapClient() {
        }
        
        public CreditSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 AdjustTip(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.TipRequest Request) {
            return base.Channel.AdjustTip(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> AdjustTipAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.TipRequest Request) {
            return base.Channel.AdjustTipAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.SignatureResponse45 AttachSignature(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.SignatureRequest Request) {
            return base.Channel.AttachSignature(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.SignatureResponse45> AttachSignatureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.SignatureRequest Request) {
            return base.Channel.AttachSignatureAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Authorize(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.AuthorizationRequest Request) {
            return base.Channel.Authorize(Credentials, PaymentData, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> AuthorizeAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.AuthorizationRequest Request) {
            return base.Channel.AuthorizeAsync(Credentials, PaymentData, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 BoardCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.BoardingRequest Request) {
            return base.Channel.BoardCard(Credentials, PaymentData, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> BoardCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.BoardingRequest Request) {
            return base.Channel.BoardCardAsync(Credentials, PaymentData, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 UpdateBoardedCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.UpdateBoardedCardRequest Request) {
            return base.Channel.UpdateBoardedCard(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> UpdateBoardedCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.UpdateBoardedCardRequest Request) {
            return base.Channel.UpdateBoardedCardAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Capture(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.CaptureRequest Request) {
            return base.Channel.Capture(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> CaptureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.CaptureRequest Request) {
            return base.Channel.CaptureAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.VaultTokenResponse45 FindBoardedCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request) {
            return base.Channel.FindBoardedCard(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultTokenResponse45> FindBoardedCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request) {
            return base.Channel.FindBoardedCardAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 ForceCapture(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.ForceCaptureRequest Request) {
            return base.Channel.ForceCapture(Credentials, PaymentData, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> ForceCaptureAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.ForceCaptureRequest Request) {
            return base.Channel.ForceCaptureAsync(Credentials, PaymentData, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Refund(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.RefundRequest Request) {
            return base.Channel.Refund(Credentials, PaymentData, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> RefundAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.RefundRequest Request) {
            return base.Channel.RefundAsync(Credentials, PaymentData, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Sale(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.SaleRequest Request) {
            return base.Channel.Sale(Credentials, PaymentData, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> SaleAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.PaymentData PaymentData, CayanCheckoutSample.MerchantWARE45.SaleRequest Request) {
            return base.Channel.SaleAsync(Credentials, PaymentData, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.BatchResponse45 SettleBatch(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials) {
            return base.Channel.SettleBatch(Credentials);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.BatchResponse45> SettleBatchAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials) {
            return base.Channel.SettleBatchAsync(Credentials);
        }
        
        public CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45 UnboardCard(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request) {
            return base.Channel.UnboardCard(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.VaultBoardingResponse45> UnboardCardAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VaultTokenRequest Request) {
            return base.Channel.UnboardCardAsync(Credentials, Request);
        }
        
        public CayanCheckoutSample.MerchantWARE45.TransactionResponse45 Void(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VoidRequest Request) {
            return base.Channel.Void(Credentials, Request);
        }
        
        public System.Threading.Tasks.Task<CayanCheckoutSample.MerchantWARE45.TransactionResponse45> VoidAsync(CayanCheckoutSample.MerchantWARE45.MerchantCredentials Credentials, CayanCheckoutSample.MerchantWARE45.VoidRequest Request) {
            return base.Channel.VoidAsync(Credentials, Request);
        }
    }
}
